### ISSUE TITLE
Безопасность 

### ISSUE THREAD

**Issue by el41n** [Alex-Sidorov/SEFOLL#2]
Пароли следует хранить в виде хешей, при чем следует ограничить длину пароля, для защиты от брута радужной таблицей и добавить 'соль'. Преимущества хэша перед шифрованием: скорость вычисления, одинаковая длина,  отсутствие необходимости хранения ключей шифрования.

**Comment by Alex-Sidorov** [comment]
Замечания приняты и будут учтены.
